import jsPDF from 'jspdf';
import type { CornellNoteDocument } from '@/types/cornell';

const A4_WIDTH = 210;
const A4_HEIGHT = 297;
const MARGIN = 15;
const HEADER_HEIGHT = 25;
const FOOTER_HEIGHT = 15;
const KEYWORD_WIDTH = 55;
const NOTES_WIDTH = A4_WIDTH - MARGIN * 2 - KEYWORD_WIDTH - 5;
const CONTENT_START_Y = MARGIN + HEADER_HEIGHT + 5;
const CONTENT_END_Y = A4_HEIGHT - MARGIN - FOOTER_HEIGHT;
const LINE_HEIGHT = 6;
const SUMMARY_LINE_HEIGHT = 5;

export function generateCornellNotesPDF(document: CornellNoteDocument): void {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  // Generate each page
  document.pages.forEach((page, index) => {
    if (index > 0) {
      pdf.addPage();
    }

    drawPageHeader(pdf, document, page.pageNumber, document.totalPages);
    drawCornellLayout(pdf);
    
    let keywordY = CONTENT_START_Y + 5;
    let notesY = CONTENT_START_Y + 5;

    // Draw keywords
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'bold');
    page.keywords.forEach((keyword) => {
      const lines = pdf.splitTextToSize(keyword, KEYWORD_WIDTH - 5);
      if (keywordY + lines.length * LINE_HEIGHT > CONTENT_END_Y - 10) return;
      
      pdf.setTextColor(102, 51, 153); // Purple for keywords
      lines.forEach((line: string) => {
        pdf.text(line, MARGIN + 2, keywordY);
        keywordY += LINE_HEIGHT;
      });
      keywordY += 3;
    });

    // Draw notes
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(0, 0, 0);
    page.notes.forEach((note) => {
      const lines = pdf.splitTextToSize(`• ${note}`, NOTES_WIDTH - 5);
      if (notesY + lines.length * LINE_HEIGHT > CONTENT_END_Y - 10) return;
      
      lines.forEach((line: string) => {
        pdf.text(line, MARGIN + KEYWORD_WIDTH + 7, notesY);
        notesY += LINE_HEIGHT;
      });
      notesY += 2;
    });

    drawPageFooter(pdf, page.pageNumber, document.totalPages);
  });

  // Add summary page if content exists
  if (document.summary) {
    pdf.addPage();
    drawSummaryPage(pdf, document);
  }

  // Save the PDF
  const fileName = `${document.title.replace(/[^a-z0-9]/gi, '_')}_Cornell_Notes.pdf`;
  pdf.save(fileName);
}

function drawPageHeader(
  pdf: jsPDF,
  document: CornellNoteDocument,
  pageNumber: number,
  totalPages: number
): void {
  // Title
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(0, 0, 0);
  pdf.text(document.title, MARGIN, MARGIN + 8);

  // Date and page info
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(100, 100, 100);
  pdf.text(`Date: ${document.date}`, MARGIN, MARGIN + 16);
  pdf.text(`Page ${pageNumber} of ${totalPages}`, A4_WIDTH - MARGIN - 25, MARGIN + 16);

  // Topic
  pdf.setFontSize(10);
  pdf.setTextColor(60, 60, 60);
  const topicText = document.topic.length > 60 
    ? document.topic.substring(0, 57) + '...' 
    : document.topic;
  pdf.text(`Topic: ${topicText}`, MARGIN, MARGIN + 22);

  // Header separator line
  pdf.setDrawColor(200, 200, 200);
  pdf.setLineWidth(0.5);
  pdf.line(MARGIN, MARGIN + HEADER_HEIGHT, A4_WIDTH - MARGIN, MARGIN + HEADER_HEIGHT);
}

function drawCornellLayout(pdf: jsPDF): void {
  // Vertical divider between keywords and notes
  pdf.setDrawColor(180, 180, 180);
  pdf.setLineWidth(0.3);
  pdf.line(
    MARGIN + KEYWORD_WIDTH,
    CONTENT_START_Y,
    MARGIN + KEYWORD_WIDTH,
    CONTENT_END_Y
  );

  // Column headers
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(100, 100, 100);
  pdf.text('KEYWORDS / QUESTIONS', MARGIN + 2, CONTENT_START_Y - 2);
  pdf.text('NOTES', MARGIN + KEYWORD_WIDTH + 7, CONTENT_START_Y - 2);
}

function drawPageFooter(pdf: jsPDF, pageNumber: number, totalPages: number): void {
  pdf.setFontSize(8);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(150, 150, 150);
  pdf.text(
    'Cornell Notes - Generated by Aqademiq',
    A4_WIDTH / 2,
    A4_HEIGHT - MARGIN,
    { align: 'center' }
  );
}

function drawSummaryPage(pdf: jsPDF, document: CornellNoteDocument): void {
  // Header
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(0, 0, 0);
  pdf.text('SUMMARY', MARGIN, MARGIN + 10);

  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(80, 80, 80);
  pdf.text(document.title, MARGIN, MARGIN + 18);

  // Divider
  pdf.setDrawColor(200, 200, 200);
  pdf.setLineWidth(0.5);
  pdf.line(MARGIN, MARGIN + 23, A4_WIDTH - MARGIN, MARGIN + 23);

  // Summary content
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(0, 0, 0);
  
  const summaryLines = pdf.splitTextToSize(document.summary, A4_WIDTH - MARGIN * 2);
  let y = MARGIN + 35;
  
  summaryLines.forEach((line: string) => {
    if (y < A4_HEIGHT - MARGIN - 20) {
      pdf.text(line, MARGIN, y);
      y += SUMMARY_LINE_HEIGHT + 1;
    }
  });

  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  pdf.text(
    `Generated on ${document.date} | Aqademiq Cornell Notes`,
    A4_WIDTH / 2,
    A4_HEIGHT - MARGIN,
    { align: 'center' }
  );
}
