// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thmyddcvpopzjbvmhbur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRobXlkZGN2cG9wempidm1oYnVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMDA3OTksImV4cCI6MjA2OTg3Njc5OX0.yomXAXLBjy_9re1xyJDRNV5rSuLfeCwwyNtH-fJxJ1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    storageKey: 'sb-thmyddcvpopzjbvmhbur-auth-token',
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js-web/2.53.0',
    },
  },
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
    heartbeatIntervalMs: 30000,
    reconnectAfterMs: (tries: number) => Math.min(tries * 1000, 30000),
  },
  db: {
    schema: 'public',
  },
});