// This file is automatically generated. Do not edit it directly.
// Re-exports the enhanced Supabase client to ensure single instance
import { supabase as enhancedSupabase } from '@/config/supabaseClient';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Re-export the enhanced client to maintain backward compatibility
// This ensures only one Supabase client instance exists across the app
export const supabase = enhancedSupabase;